# Generated by Django 2.0.7 on 2021-07-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uom_uom',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category_id', models.IntegerField()),
                ('factor', models.FloatField()),
                ('rounding', models.FloatField()),
                ('active', models.BooleanField()),
                ('uom_type', models.CharField(max_length=100)),
                ('measure_type', models.CharField(max_length=100)),
                ('create_uid', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('write_uid', models.IntegerField()),
                ('write_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'uom_uom',
            },
        ),
        migrations.CreateModel(
            name='Utm_campaign',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('stage_id', models.IntegerField()),
                ('is_website', models.BooleanField()),
                ('color', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('create_uid', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('write_uid', models.IntegerField()),
                ('write_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'utm_campaign',
            },
        ),
        migrations.CreateModel(
            name='Utm_medium',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField()),
                ('create_uid', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('write_uid', models.IntegerField()),
                ('write_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'utm_medium',
            },
        ),
        migrations.CreateModel(
            name='Utm_source',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('create_uid', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('write_uid', models.IntegerField()),
                ('write_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'utm_source',
            },
        ),
    ]
