# Generated by Django 2.0.7 on 2021-07-14 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_main_attachment_id', models.IntegerField()),
                ('default_code', models.CharField(max_length=10)),
                ('active', models.BooleanField()),
                ('product_tmpl_id', models.IntegerField()),
                ('barcode', models.CharField(max_length=10)),
                ('combination_indices', models.CharField(max_length=10)),
                ('volume', models.FloatField()),
                ('weight', models.FloatField()),
                ('can_image_variant_1024_be_zoomed', models.BooleanField()),
                ('create_uid', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('write_uid', models.CharField(max_length=10)),
                ('write_date', models.DateTimeField(default=datetime.datetime(2021, 7, 14, 14, 11, 55, 632365))),
            ],
            options={
                'db_table': 'product_product',
            },
        ),
    ]
