# Generated by Django 2.0.7 on 2021-07-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('company_id', models.IntegerField()),
                ('default_lang_id', models.IntegerField()),
                ('auto_redirect_lang', models.BooleanField()),
                ('social_twitter', models.CharField(max_length=100)),
                ('social_facebook', models.CharField(max_length=100)),
                ('social_github', models.CharField(max_length=100)),
                ('social_linkedin', models.CharField(max_length=100)),
                ('social_youtube', models.CharField(max_length=100)),
                ('social_instagram', models.CharField(max_length=100)),
                ('google_analytics_key', models.CharField(max_length=100)),
                ('google_management_client_id', models.CharField(max_length=100)),
                ('google_management_client_secret', models.CharField(max_length=100)),
                ('google_maps_api_key', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('cdn_activated', models.BooleanField()),
                ('cdn_url', models.CharField(max_length=100)),
                ('cdn_filters', models.CharField(max_length=100)),
                ('homepage_id', models.IntegerField()),
                ('theme_id', models.IntegerField()),
                ('specific_user_account', models.BooleanField()),
                ('auth_signup_uninvited', models.CharField(max_length=100)),
                ('website_form_enable_metadata', models.BooleanField()),
                ('create_uid', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('write_uid', models.IntegerField()),
                ('write_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'webiste',
            },
        ),
    ]
